#ifndef COLOR_H
#define COLOR_H

typedef enum {
    COLOR_PAIR_UNKNOWN = -1,
    COLOR_PAIR_VOID = 0,
    COLOR_PAIR_WALL,
    COLOR_PAIR_FLOOR,
    COLOR_PAIR_ROAD,
    COLOR_PAIR_PLAYER,
    COLOR_PAIR_STATUS,
    COLOR_PAIR_ENEMY,

    // Enemy colors
    COLOR_PAIR_ENEMY_RAT,
    COLOR_PAIR_ENEMY_GOBLIN,
    COLOR_PAIR_ENEMY_ORC,
    COLOR_PAIR_ENEMY_SNAKE,
    COLOR_PAIR_ENEMY_ZOMBIE,
    COLOR_PAIR_ENEMY_BAT,

    COLOR_PAIR_EXIT
} ColorPair;

void init_colors(void);

#endif // COLOR_H
